version: '3.8'

services:
  pong:
    container_name: pong
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - DATABASE_URL=postgresql://django_user:django_password@db:5432/django_db
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: pong_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password

volumes:
  postgres_data:
